language: java
"dist": "trusty"
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
addons:
  apt:
    packages:
      - openjdk-6-jdk
before_install:
        - echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc
        - TRAVIS_JDK_VERSION=openjdk6
