language: java
"dist": "precise"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install: 
 # for gh-311 (modify to use the TLSv1.2 on Java 7) 
 - export _JAVA_OPTIONS=-Dhttps.protocols=TLSv1.1,TLSv1.2
