language: java
"dist": "trusty"
addons:
  apt:
    packages:
      - openjdk-6-jdk
matrix:
  include:
    - env: JDK='OpenJDK 6'
      before_install:
        - echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc
        - TRAVIS_JDK_VERSION=openjdk6
        - export _JAVA_OPTIONS=-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
