language: java
"dist": "trusty"
addons:
  apt:
    packages:
      - openjdk-6-jdk
matrix:
  include:
    - env: JDK='OpenJDK 6'
      before_install:
        - echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc
        - TRAVIS_JDK_VERSION=openjdk6      
jdk:
  - openjdk6
  - oraclejdk8
  - openjdk7
